### PR TITLE
[OpenCage] Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by jbelien**

### CODE REVIEW

**Comment by jbelien** [comment]
@Nyholm 
I would like to release version 4.2 of OpenCage provider but I have the following errors.

- OpenCage (see [Travis](https://travis-ci.org/geocoder-php/open-cage-provider/builds/482467597#L514)) : 
  ```
  call_user_func() expects parameter 1 to be a valid callback, class '\Nyholm\Psr7\Httplug\DiscoveryStrategy' not found
  ```

- MaxMindBinary (see [Travis](https://travis-ci.org/geocoder-php/Geocoder/jobs/482467483#L652))
  ```
  Declaration of Http\Client\Curl\Client::sendRequest(Psr\Http\Message\RequestInterface $request) must be compatible with Http\Client\HttpClient::sendRequest(Psr\Http\Message\RequestInterface $request): Psr\Http\Message\ResponseInterface in /home/travis/build/geocoder-php/Geocoder/vendor/php-http/curl-client/src/Client.php on line 27
  ```

Any idea how to fix both of those issues ?

**Comment by Nyholm** [comment]
I will merge because failure are unrelated. 

They are fixed in #934

**Comment by Nyholm** [comment]
Thank you

**Comment by jbelien** [comment]
Thanks a lot 👍

**Pull request merged**
