### PR TITLE
Update IpInfoDb.php

### PR DESCRIPTION
**Pull request by rtiagom**
Patch to prevent "Uncaught TypeError: Argument 11 passed to Geocoder\Model\Address".

### CODE REVIEW

**Review by jbelien — CHANGES_REQUESTED** [review]
Not sure this is the best way to tackle this issue.
I would prefer to process correctly the timezone in every cases!

Could you also add a test with an IP in Australia ?

Thanks!

**Comment by rtiagom** [comment]
I agree that this is not the best way to handle this issue but I don't have the time to work on a proper fix right now. At least the patch makes everything work with Geocoder\Model\Address.

**Comment by rtiagom** [comment]
Regarding the test IP, remember that the reason an Australian IP fails right now is because of daylight saving time and that changes in a few months which would make the test inconclusive.

I would recommend applying the current patch right now and open a ticket to find an alternative to timezone_name_from_abbr later on.

**Comment by jbelien** [comment]
> At least the patch makes everything work with Geocoder\Model\Address.

> I would recommend applying the current patch right now and open a ticket to find an alternative to timezone_name_from_abbr later on.

I don't really consider "hiding" the error to be a patch.

> Regarding the test IP, remember that the reason an Australian IP fails right now is because of daylight saving time and that changes in a few months which would make the test inconclusive.

We store/cache the API response, the test will be the same at anytime.

**Comment by rtiagom** [comment]
> I don't really consider "hiding" the error to be a patch.

Ok, fair enough. I don't have the time to work on this.  In our current project we have no need to use the Address timezone field so it doesn't matter what it returns as long it doesn't break which this patch handles it. Feel free to reject the PR.

**Pull request closed without merging**
