### PR TITLE
chore: add testruns for PHP 8.4

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Comment by ruudk** [comment]
Thanks for doing this. 

@jbelien What's needed to get this merged? Anything I can do to help?

**Comment by ruudk** [comment]
@Nyholm Would you be able to help out with this?

**Comment by Chris53897** [comment]
There is one failing test for PHP 8.4 low.
https://github.com/geocoder-php/Geocoder/actions/runs/11325637108/job/31492962515?pr=1235

I guess we need to bump the minimum version of http-client?  [v7.0.10](https://github.com/symfony/symfony/releases/tag/v7.0.10) ?

**Comment by ruudk** [comment]
Since `symfony/http-client` is a dev dependency, I think this is fine to do.

We can change it to:
```diff
-"symfony/http-client": "^5.4 || ^6.4 || ^7.0",
+"symfony/http-client": "^5.4 || ^6.4 || ^7.0.10",
```

**Review by jbelien — APPROVED** [review]

**Comment by Chris53897** [comment]
I bumped the min version to ^5.4.45 to solve it.

**Review by Nyholm — APPROVED** [review]
I think it looks good

**Comment by ruudk** [comment]
@Chris53897 Looks good, only a few PHP CS Fixer issues left and we can ship it! 🎉

**Comment by Chris53897** [comment]
I have created a seperate PR for this.Am 14.11.2024 um 10:04 schrieb Ruud Kamphuis ***@***.***>:﻿
@Chris53897 Looks good, only a few PHP CS Fixer issues left and we can ship it! 🎉

**Comment by ruudk** [comment]
Why, would have been easier for everyone if it was done in this one, so we could have just merged it and be done with it. Now you have to rebase this PR later again.

**Pull request merged**
