### PR TITLE
Added changelog for Nominatim

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by jbelien** [comment]
Possible to merge it and publish the new version on Packagist ? :)
Thanks !

**Comment by Nyholm** [comment]
Sure. I just waiting for reviews by the community. Can you confirm that that master version of Nominatim is working as expected?

**Comment by jbelien** [comment]
Probably not the most objective one on that topic since I made the changes but I can confirm it works ! :)

Probably best to wait to someone else to try it ^^

**Comment by Nyholm** [comment]
Im fine with that =)

**Comment by Nyholm** [comment]
4.1.0 released.

**Comment by jbelien** [comment]
Tack så mycket !

**Pull request merged**
