### PR TITLE
Use AbstractHttpProvider in FreeGeoIp

### PR DESCRIPTION
**Pull request by Stadly**
Use `getRequest` and `getParsedResponse` from `AbstractHttpProvider` instead of duplicating code in `FreeGeoIp`. See https://github.com/geocoder-php/Geocoder/pull/864.

### CODE REVIEW

**Comment by Nyholm** [comment]
It looks good. I need to make a new release of the http-common-provider.

**Comment by Stadly** [comment]
Ok

**Comment by Nyholm** [comment]
You need to update composer.json for this provider to `geocoder-php/common-http:^4.1`

**Comment by Stadly** [comment]
Done. Didn't help Travis, though.

**Pull request merged**
