### PR TITLE
Added small clarifications for string formatter.

### PR DESCRIPTION
**Pull request by leevigraham**

### CODE REVIEW

**Comment by leevigraham** [comment]
@willdurand Would you like me to fix the styleci issues given they are not directly related to this PR?

**Comment by willdurand** [comment]
@leevigraham this could be done in a separate PR, WDYT?

**Comment by leevigraham** [comment]
@willdurand, Makes sense. I'll tackle it tonight. 👍

**Comment by leevigraham** [comment]
@willdurand StyleCi updated in #799.

**Pull request merged**
