### PR TITLE
Improve error message in case a provider can NOT geocode an address / query

### PR DESCRIPTION
**Pull request by holtkamp**
in case a provider can NOT geocode an address / query

### CODE REVIEW

**Comment by holtkamp** [comment]
@Nyholm to be honest, I did not check. This one appeared in my logs and seemed "strange" to me 😉

**Comment by holtkamp** [comment]
@Nyholm when thinking of it, I personally would use:

```php 
$logger->alert('Some informational message', $context = [ ... ]);
```
instead of 
```php 
$logger->log('alert', 'Some informational message', $context = [ ... ]);
```
I suppose LoggerInterface::log() should only be used when the severity level is a variable / determined dynamically...

**Comment by Nyholm** [comment]
You may be correct. I do not mind either way.

**Comment by holtkamp** [comment]
Will have a look to all logging messages coming time and see where such improvements can be applied in a separate PR. This is more a "bug fix" in my opinion, as the message was plain wrong 🤓

**Comment by Nyholm** [comment]
Okey. Thank you

**Comment by holtkamp** [comment]
@Nyholm any chance this PR lands in a "patch" version? I guess `4.0.1` (has it been that long since a release? Impressive stability!

**Comment by holtkamp** [comment]
@Nyholm is a new patch release something which can be considered?

**Comment by jbelien** [comment]
Sorry @holtkamp , I think we forgot about this.
I'll release `geocoder-php/chain-provider` `4.0.1` ASAP ! 👍

**Comment by Nyholm** [comment]
Yeah, that sounds like a great idea. 

Could we do a small PR to the change log of the chain provider?

**Comment by jbelien** [comment]
> Could we do a small PR to the change log of the chain provider?

Already on it :P

**Comment by jbelien** [comment]
Done : https://packagist.org/packages/geocoder-php/chain-provider#4.0.1

Thanks for the reminder @holtkamp 🎉

**Comment by holtkamp** [comment]
mm, I now see that the reverse query logging has the same "issue": https://github.com/geocoder-php/chain-provider/blob/master/Chain.php#L106-L109

**Comment by jbelien** [comment]
Indeed, I'm on it ! :)

**Comment by jbelien** [comment]
@holtkamp Done: https://packagist.org/packages/geocoder-php/chain-provider 🎉

**Comment by simonschaufi** [comment]
@holtkamp  Hi, I have the problem, that the placeholders don't get replaced any more in my error message after this change.
My error message looks like this: `Provider "{providerName}" could not geocode address: "{address}".`. I don't see any point where the placeholders get replaced. I guess something like sprintf is missing (which was there before but got dropped).

**Comment by holtkamp** [comment]
Hi @simonschaufi, what implementation of the PSR Logger are you using?

When reading the specs it seems that support for "placeholders" is an optional feature. 

https://www.php-fig.org/psr/psr-3/

I use https://github.com/Seldaek/monolog which *does* support placeholders...

**Comment by simonschaufi** [comment]
Hi @holtkamp, I use Laravel Framework which has a wrapper Class for `monolog/monolog` (installed: 1.24.0). I debugged the whole logging and don't find the point where there is any replacement within the message

**Comment by holtkamp** [comment]
And does your Monolog logger use the [PsrLogMessageProcessor](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#processors)

The documentation states:

>Processes a log record's message according to PSR-3 rules, replacing {foo} with the value from $context['foo'].

**Comment by simonschaufi** [comment]
This is the sub package: https://github.com/illuminate/log Couldn't find it there. What exactly is missing to make that work? I will make a PR then to add the feature in Laravel

**Comment by holtkamp** [comment]
Well, I am not very familiar with Laravel, but some searches give me:

https://stackoverflow.com/questions/51694036/laravel-5-6-how-to-push-monolog-processor
https://hotexamples.com/examples/illuminate.log/Writer/getMonolog/php-writer-getmonolog-method-examples.html


But maybe we need to revert to using `sprintf()` instead of `{placeholders}`. I was not aware that support for placeholders is optional for PSR Loggers. @jbelien what do you think?

**Pull request merged**
