### PR TITLE
Added locale support

### PR DESCRIPTION
**Pull request by shtricul**
Tested on 'ru', 'de' locale

### CODE REVIEW

**Comment by willdurand** [comment]
Would you mind add a test case for that? Thanks!

**Comment by shtricul** [comment]
My ip - 91.230.191.2, it's Russia.
With `'locale' => 'ru'` will be `locality: "Ковров"`.
With `'locale' => 'en'` will be `locality: "Kovrov"`.

Or you ask me to write a test for this provider with several `locale` parameters?

**Comment by willdurand** [comment]
Yep, it would me nice to have a PHP test case with what you provided here.

**Comment by toin0u** [comment]
Thanks @shtricul :+1: It looks good :)

**Comment by toin0u** [comment]
Maybe you can add a note here https://github.com/geocoder-php/Geocoder#ip-based-providers about the possibility to add a locale and if not the `en-US` will be used :)

**Comment by willdurand** [comment]
> Maybe you can add a note here https://github.com/geocoder-php/Geocoder#ip-based-providers about the possibility to add a locale and if not the en-US will be used :)
>  Show all checks

:+1:

**Comment by willdurand** [comment]
@shtricul could you please update the doc?

**Comment by Nyholm** [comment]
I like this PR. There are a few things that is needed before I can merge: 

* Documentation
* Rebase
* Remove Ivory stuff.

**Comment by Nyholm** [comment]
Ping, will you complete the work on this PR or should it be closed?

**Comment by shtricul** [comment]
@Nyholm sorry for so long feedback. I will fix all comments until June, 11.

**Comment by Nyholm** [comment]
Awesome. That would be great. Be aware of the changes in master and the new `GeocodeQuery`.

**Comment by shtricul** [comment]
Made a new pull request [here](https://github.com/geocoder-php/Geocoder/pull/676).

**Pull request closed without merging**
