### PR TITLE
Integrate Geoportail.lu geocoder

### PR DESCRIPTION
**Pull request by frantzmiccoli**

### CODE REVIEW

**Comment by jbelien** [comment]
Hello @frantzmiccoli ,

Thanks a lot for your contribution ! 👍 

Before adding your provider to our list of third-party providers, could you use `Geocoder\IntegrationTest\BaseTestCase` in your test ?
You can check the tests of any of our providers to see how it works.

Thanks !

**Comment by frantzmiccoli** [comment]
Hi!

I will try to do this in the next days.

Thanks,

**Comment by frantzmiccoli** [comment]
Hi @jbelien 

It took me a bit more time to find time but it is done ;)

Thanks,

**Comment by jbelien** [comment]
See https://github.com/frantzmiccoli/geocoder-php-geoportail-lu/pull/1

**Comment by frantzmiccoli** [comment]
Accepted ;)

**Pull request merged**
