### PR TITLE
Add PHP 8.1 support by specifying return types for `getIterator` and `count`

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@jbelien Would be great to have this merged to allow people to run Geocoder on PHP 8.1 that is expected to be released next week. 🙏

**Comment by jbelien** [comment]
Thank you for your contribution @ruudk.

Could you explain why support for PHP8.1 requires updating `AddressCollection.php` and `AdminLevelCollection.php` ? Thanks.

**Comment by ruudk** [comment]
Because PHP 8.1 adds return types and parameter types for almost all built in interfaces and functions.

**Comment by jbelien** [comment]
Ping me again when PHP8.1 is released, I'll merge this then.

**Review by jbelien — APPROVED** [review]

**Comment by ruudk** [comment]
It can already be merged as these changes are backwards compatible. PHP 8.1 Will be released next week :)

**Comment by ruudk** [comment]
Can this be merged please? :)

**Comment by ruudk** [comment]
Thanks, can it also be tagged?

**Pull request merged**
