### PR TITLE
[Yandex] Location "kind" addition

### PR DESCRIPTION
**Pull request by ReDev1L**
Pull request adds "Location kind":
https://tech.yandex.ru/maps/doc/geocoder/desc/reference/kind-docpage/

Actually nothing special here

### CODE REVIEW

**Comment by jbelien** [comment]
Thanks a lot @ReDev1L 

Could you add this new "field" in the tests ?

**Comment by ReDev1L** [comment]
> Thanks a lot @ReDev1L
> 
> Could you add this new "field" in the tests ?

Dunno if it(yandex geocoder API) will return right kind for test, dont have phpunit atm, will fix later if not

**Comment by jbelien** [comment]
Test seems okay 👍 

But could you add it for the other tests as well ?
Thanks !

**Comment by ReDev1L** [comment]
You dont have "name", "precision"(and now "kind") properties assertion for in other tests, because other tests based on Location interface, not on YandexAddress model. I wont add them, you should split that task in another issue, because small refactor of tests required

**Comment by jbelien** [comment]
Indeed, you're right !

I'll merge your PR in the next few days !
Thanks a lot ! 👍 

And if you have the courage to update the tests with `YandexAddress` model, feel free to sumbit a new PR 😄

**Comment by ReDev1L** [comment]
Thank you too. My courage will be depleted today, because i need to get Russian federal subjects by yandex geocoder :))

**Comment by jbelien** [comment]
I updated the tests : #919

**Comment by jbelien** [comment]
@ReDev1L Version 4.1.0 is released : https://github.com/geocoder-php/yandex-provider/releases/tag/4.1.0

Thanks again for your help 👍

**Comment by ReDev1L** [comment]
Thank you too =)

**Pull request merged**
