### PR TITLE
Nominatim geocoder cannot handle IP addresses

### PR DESCRIPTION
**Pull request by mtmail**
Nominatim has no such feature.

The tests sent `127.0.0.1` and expected `localhost` in the response but that response is hardcoded in the AbstractProvider and never came from Nominatim.

Adjusted the tests. `phpunit` passes for me.

### CODE REVIEW

**Comment by mtmail** [comment]
Makes sense. I added a changelog entry now and upgrade from 4.1=>5.0.

I assume PHP packagist takes the version number directly from the changelog? At least I couldn't find any other mention of 4.1 in other files.

**Comment by Nyholm** [comment]
I (or some other maintainer) have to make a release. Packagist looks at all the releases. 

I think this looks good. I’ll to a more detailed review later. Or maybe @jbelien wants to take a look?

**Comment by jbelien** [comment]
@Nyholm Let me just fix the issue with the headers (User-Agent and Referer) - see #853 - before creating a new release, I'll take care of that in the next few days 😃

**Comment by jbelien** [comment]
PR #873 is ready to be reviewed.
Once both PR #859 and #873 are merged I think we can release version `5.0` of **Nominatim** provider !👍

**Comment by jbelien** [comment]
I think we can merge this PR and release version `5.0` ! 🎉

**Pull request merged**
