### PR TITLE
Added 'short_name' field for street name for google maps

### PR DESCRIPTION
**Pull request by Tiraniel**
Added short street name field for Google Maps provider

### CODE REVIEW

**Comment by jbelien** [comment]
Hello @Tiraniel 

Thanks a lot for your contribution !
Could you make sure the tests succeed by adding the `.cached_response` for your new `testStreetShortNameWithRealAddress()` test ?

Thanks.

**Comment by Tiraniel** [comment]
Hello @jbelien 

Thanks for response. This is my first contribution attempt. Sure I'll make changes.

**Comment by jbelien** [comment]
Thanks a lot @Tiraniel ! Looking much better ! 👍 

I realize that every component has a `long_name` and a `short_name`. Why limit your PR to `route` only ? Could you extend it to every component ?

PS: The test still fails but I'm having a look at it, don't worry about that.

**Comment by Tiraniel** [comment]
Sure. I can extend components with sort_name. Thanks for review!

**Comment by jbelien** [comment]
Hello @Tiraniel , any chance you could work on this ?

PS: It will need a rebase to apply our last updates.

**Comment by atymic** [comment]
Can pick this one up if help is required :smile:

**Comment by jbelien** [comment]
@Tiraniel Any chance you could finish this PR ? Thanks.

**Pull request closed without merging**
