### PR TITLE
Add countrycode to Bing api calls

### PR DESCRIPTION
**Pull request by belendel**
By default only country name is retreived from Bing Maps. With an extra request parameter the country code can be retreived as well.

### CODE REVIEW

**Comment by Baachi** [comment]
Cool thanks!

**Comment by willdurand** [comment]
\o/

**Comment by FredoVelcro** [comment]
:+1: 
@willdurand 
Can you merge this PR please ? I need the country code too !
Thank you !

**Comment by willdurand** [comment]
mmh this is merged, isn't it?

**Comment by FredoVelcro** [comment]
oh sorry ! my package was not up to date...

**Comment by FredoVelcro** [comment]
Can you upgrade the GeocoderBundle so that it takes Geocoder lib ~3.1 please ?

**Pull request merged**
