### PR TITLE
Include the postalcode in the reverse query as well in TomTom provider

### PR DESCRIPTION
**Pull request by Spriz**
I'd guess this line was left out by accident - but never the less it would be nice to have it here as well :-)

### CODE REVIEW

**Comment by Spriz** [comment]
I just copied the line from https://github.com/Spriz/Geocoder/blob/patch-1/src/Provider/TomTom/TomTom.php#L102 btw

**Comment by jbelien** [comment]
Thanks a lot @Spriz 👍 
Could you add the postal code to the test as well ? Thanks!

**Review by Spriz — COMMENTED** [review]
Check for postal code being not-null in tests as well

**Comment by Spriz** [comment]
@jbelien Done! :+1:

**Comment by jbelien** [comment]
Thanks @Spriz !
A new release has been published: https://packagist.org/packages/geocoder-php/tomtom-provider#4.4.0

**Pull request merged**
