### PR TITLE
Add extension methods for get Geoname data

### PR DESCRIPTION
**Pull request by NSViking**
On this commit I make any methods for expand geonames utlity, with this methods you can get all countries on the World, the biggest cities of a Country.

And this methods give you the posibility to obtain a list of countries, and get and countryID and obtain all states of this country, get stateID and get all regions of this state, and get all cities with this last regionID.

### CODE REVIEW

**Comment by Nyholm** [comment]
Hey. Sorry for the late response. 
I like this. Could you rebase and add some tests?

**Comment by Nyholm** [comment]
Ping

**Comment by Nyholm** [comment]
Hey. I will close this after 2 weeks if there is not interest in continue the work.

**Comment by SrihariThalla** [comment]
Hey @NSViking,

I'd like to take over this PR if you have other priorities. Let me know!

cc @Nyholm

**Comment by Nyholm** [comment]
Awesome @SrihariThalla. Please do. I would be happy to review it.

**Comment by NSViking** [comment]
Hey @SrihariThalla!

At now is very difficult for me finish this work, but if you want it you can work on this and we can improve it together in the future. Thanks!!

cc @Nyholm

**Comment by Nyholm** [comment]
Closing this because of inactivity. Feel free to open a new PR if you want to continue this work

**Pull request closed without merging**
