### PR TITLE
add detailed location gmaps

### PR DESCRIPTION
**Pull request by TNAJanssen**
Add neighborhood and Sublocality levels so get more detailed information.

For example here in the netherlands a city is cut into pieces, like east, centrum etc

### CODE REVIEW

**Comment by Nyholm** [comment]
Im not sure why you open another PR with the same feature. You can just update the code in the existing branch. 

Does all providers provide sublocallity?

**Comment by TNAJanssen** [comment]
@Nyholm i couldn't change the target branch, and you wanted it to be in the master so thats why! 

I haven't looked at other providers yet, so i won't know!

**Comment by Nyholm** [comment]
Ah, okey. I see. 

What provider have you looked at?
It seams like this data is actually AdminLevel data. What if you update your provider to include the sublocallity?

**Comment by TNAJanssen** [comment]
https://developers.google.com/maps/documentation/geocoding/intro

Also i have added neighborhood, this wasn't anywhere in the code yet

"sublocality indicates a first-order civil entity below a locality. For some locations may receive one of the additional types: sublocality_level_1 to sublocality_level_5. Each sublocality level is a civil entity. Larger numbers indicate a smaller geographic area."

"administrative_area_level_1 indicates a first-order civil entity below the country level. Within the United States, these administrative levels are states. Not all nations exhibit these administrative levels. In most cases, administrative_area_level_1 short names will closely match ISO 3166-2 subdivisions and other widely circulated lists; however this is not guaranteed as our geocoding results are based on a variety of signals and location data.
"

**Comment by Nyholm** [comment]
Okey, I see. This is a very google maps feature. I do like it and I think it should be possible to access sublocallity on version 4.0. 
I will put this feature on hold for now. I will revisit when we are closer to 4.0.

**Comment by Nyholm** [comment]
Hey @TNAJanssen. 

There has been a lots of changes in master since you made this PR. There is now a custom Google response where this change should be added. Can you rebase this PR and make sure you add the changes to the `GoogleAddress` instead of the shared one?

**Comment by Nyholm** [comment]
Ping

**Comment by TNAJanssen** [comment]
Hey @Nyholm 

I will do that but i won't have time for it this week, next week i will do it!

Thanks

**Comment by Nyholm** [comment]
Awesome!

**Comment by Nyholm** [comment]
Friendly ping: Any updates here?

**Comment by Nyholm** [comment]
Im closing this PR because of inactivity. Feel free to pick up the work and create a new PR.

**Pull request closed without merging**
