### PR TITLE
Improve for opencage provider

### PR DESCRIPTION
**Pull request by eugenekurasov**
https://github.com/geocoder-php/Geocoder/issues/855 have offered use more data.

Added model `OpencageAddress`.
I added only two extra fields: geohash and formatted address.

### CODE REVIEW

**Comment by eugenekurasov** [comment]
@jbelien review please.

**Comment by jbelien** [comment]
Thanks a lot @eugenekurasov ! 👍 
I'll review this ASAP (but probably later this week) !

**Comment by eugenekurasov** [comment]
ping @jbelien

**Comment by jbelien** [comment]
Thanks a lot @eugenekurasov 👍 

I added MGRS, Maidenhead and what3words in the model, so we can close #855 !

**Pull request merged**
