### PR TITLE
Create a virtual package for provider implementation

### PR DESCRIPTION
**Pull request by Nyholm**
This will create a page at Packagist with all packages that can be used as a provider.

### CODE REVIEW

**Comment by willdurand** [comment]
👍

**Comment by Nyholm** [comment]
Thank you

**Comment by willdurand** [comment]
@Nyholm thank you for your awesome work! I love your contributions to this project. I am really honored to have you on board, and this project clearly needed someone like you. I have been very lucky. Thank you!

**Comment by Nyholm** [comment]
Thank you for your kind words. I hope the users also will appreciate the changes. 
It seams like I going to hold my deadline to release 4.0 before 31st of July.

**Pull request merged**
