### PR TITLE
Add Coordinates::toArray

### PR DESCRIPTION
**Pull request by Mechazawa**

### CODE REVIEW

**Comment by Nyholm** [comment]
Could you give me some more background why we should have this?

**Comment by Mechazawa** [comment]
For our use-case we need to get the coordinates as a tuple. Instead of having to do this every time a nice helper method would be nice. 

```php
$geoCoordinates = $address->getCoordinates();
$coordinates = [$geoCoordinates->getLatitude(), $geoCoordinates->getLongitude()];
```

**Comment by jbelien** [comment]
I like the `toArray()` idea **but** I would put **`[lon, lat]`** instead of `[lat, lon]` to respect standards ; see [GeoJSON standard](https://tools.ietf.org/html/rfc7946#appendix-A) for instance : 
> Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, and latitude for geographic coordinates)

**Comment by Mechazawa** [comment]
I've flipped the response tuple

**Pull request merged**
