### PR TITLE
Adding cookbook

### PR DESCRIPTION
**Pull request by Nyholm**
Im not sure if we want this in the readme since it it out of scope. But is (IMHO) a really common use case and it would be nice for our users not having to figure this out themselves.

### CODE REVIEW

**Comment by willdurand** [comment]
It makes sense to have this in the doc. Maybe we could have a cookbook section or a FAQ? So that it clearlly indicates that this is out of this library's scope. What?

**Comment by Nyholm** [comment]
I've started a new cookbook. =)

**Comment by Nyholm** [comment]
I changed the title of this PR. I've added a cookbook with two entries: 
* how to use cache
* how to configure the HTTP client

These are normal uses but they are not in the scope for this library.

**Comment by stevevance** [comment]
@Nyholm I already used your cache cookbook after stumbling upon it in the issues. Thanks for that!

**Comment by Nyholm** [comment]
Im happy you got use of it!

Im just waiting for someone in the Geocoder team to review and merge.

**Comment by willdurand** [comment]
🎉

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
