### PR TITLE
fix: update algolia places

### LINKED ISSUE #960: Algolia places provider is not working anymore
Algolia Places response structure changed, therefore the provider is not working anymore. 
Algolia added localized names (client expects value but it instead sees another array):
https://community.algolia.com/places/api-clients.html#json-answer

Algolia is also missing its factory.

### PR DESCRIPTION
**Pull request by atymic**
- Fix failed response parsing if locale was missing
- Add tests to cover above case
- Clean up code
- Update docs

Closes #960

### CODE REVIEW

**Comment by Fabex** [comment]
Nice, thank you @atymic.
I was no time to work on it

**Comment by atymic** [comment]
No worries 😄

**Comment by jbelien** [comment]
Awesome 🎉 
Thanks @atymic !

**Comment by atymic** [comment]
No worries @jbelien 👍

**Pull request merged**
