### PR TITLE
Add support to Here CIT environment

### PR DESCRIPTION
**Pull request by DamienHarper**
Add support to Here CIT (Customer Integration Testing) environment

### CODE REVIEW

**Comment by jbelien** [comment]
I didn't know about the Customer Integration Testing environment!
Here is a bit more information about it : https://developer.here.com/documentation/places/common/request-cit-environment.html

Thanks @DamienHarper ; I'll merge it ASAP !

**Comment by DamienHarper** [comment]
@jbelien any ETA about this?

**Comment by jbelien** [comment]
It is merged.
I now need to wait that [](https://github.com/geocoder-php/here-provider) is updated to create a new release.

It's usually faster. If it takes too long, I'll check why with @Nyholm.

**Comment by DamienHarper** [comment]
@jbelien thanks!

**Comment by jbelien** [comment]
@DamienHarper New release is live : https://packagist.org/packages/geocoder-php/here-provider

**Pull request merged**
