### PR TITLE
Make sure we dont include multiple vendor folders

### PR DESCRIPTION
**Pull request by Nyholm**
This will fail until [php-http/discovery](https://packagist.org/packages/php-http/discovery):1.6 is released (Any hour now). 

This will help #933

### CODE REVIEW

**Comment by jbelien** [comment]
Just restarted the build since [php-http/discovery](https://packagist.org/packages/php-http/discovery):1.6 is released.

Build still fails but it's due to "Array to string conversion" in PHP7.2. I'll fix it in a different PR ASAP ! 😃

**Comment by jbelien** [comment]
Oh, that's weird, I don't see the "Array to string conversion" in the Travis log ...
Well, not sure how to fix this then :/

**Comment by Nyholm** [comment]
I believe if we merge and tag this: https://github.com/geocoder-php/provider-integration-tests/pull/16

Then this PR will finally be happy =)

**Comment by Nyholm** [comment]
Thank you

**Comment by jbelien** [comment]
Awesome!
We're back in the green :P

**Comment by Nyholm** [comment]
Wohoo

**Pull request merged**
