### PR TITLE
Use https transport in Yandex provider

### PR DESCRIPTION
**Pull request by nitso**

### CODE REVIEW

**Comment by Baachi** [comment]
You have to change the exception message in the unit tests.

**Comment by willdurand** [comment]
Also, I would prefer to keep the `http` version. Some other providers have a `$useSsl` option.

**Comment by toin0u** [comment]
I also think the `$useSsl` option is the best approach https://github.com/geocoder-php/Geocoder/blob/master/src%2FGeocoder%2FProvider%2FGoogleMaps.php#L80 :)

**Comment by toin0u** [comment]
Oh Yandex will deprecate http https://github.com/geocoder-php/Geocoder/issues/431.. So this PR makes sense :) But like @Baachi said, tests should be fixed :)
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L41
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L51
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L61
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L71
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L81
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L249
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L259
- https://github.com/geocoder-php/Geocoder/blob/master/tests%2FGeocoder%2FTests%2FProvider%2FYandexTest.php#L269

**Comment by nitso** [comment]
It is a good idea to implement ```$useSsl``` switch. Should it be true or false by default?

**Comment by toin0u** [comment]
I'm not sure because Yandex will use https only soon..

**Comment by Baachi** [comment]
I would rather throw an exception if the `openssl` extension isn't installed, because Yandex didn't support `http` longer.

**Comment by willdurand** [comment]
Well if `http` is deprecated, then no need to introduce the `useSsl` option. However, it implies a sort of _soft_ BC break... I am not sure about how to deal with that..

**Comment by nitso** [comment]
I've fixed tests that mentioned http. But there is still one failing. Can't really say why.

**Comment by willdurand** [comment]
sounds good to me. could you please squash your commits?

**Comment by nitso** [comment]
Done. 

I've added cached responses as well.

**Comment by willdurand** [comment]
thank you very much!

**Pull request merged**
