### PR TITLE
Feature/update googlemaps reverse url

### PR DESCRIPTION
**Pull request by arubacao**
PR for #550

### CODE REVIEW

**Comment by Nyholm** [comment]
Awesome @arubacao. Thank you. I like that you added an issue before and then wrote proper tests. Good job!

**Comment by arubacao** [comment]
No need to thank me @Nyholm! Great to see that things are going forward after your interfaces PR! Keep up the great work

**Comment by Nyholm** [comment]
Thank you. I've created a milestone for 4.0. My plan is to have a release candidate in January. 
Contributions and PR reviews are much appreciated. 

https://github.com/geocoder-php/Geocoder/milestone/3

**Comment by arubacao** [comment]
Sorry for the late response.
I spend the last couple of days with my family and didn't have time to check github.
When I'm back to "normal" I'll be happy to make some contributions that hopefully be supportive.

**Pull request merged**
