### PR TITLE
GeocodeQuery with Ambiguous results

### PR DESCRIPTION
**Pull request by IvanBinzz**
Added functionality according documentation: https://opencagedata.com/api#ambiguous-results

### CODE REVIEW

**Comment by IvanBinzz** [comment]
@jbelien Tests already completed

**Comment by jbelien** [comment]
Looking great ! 👍 

Could you also add tests for `bounds` and `proximity` ?
Thanks.

**Comment by jbelien** [comment]
Thanks !
I'll merge this ASAP ! Great work \o/

**Comment by jbelien** [comment]
Version `4.3.0` of  `geocoder-php/open-cage-provider` is released ! 🎉

**Pull request merged**
