### PR TITLE
Add IpInfo provider

### PR DESCRIPTION
**Pull request by romainneutron**
This adds support for ipinfo.io

### CODE REVIEW

**Comment by romainneutron** [comment]
Oh, by the way it fixes #800

**Comment by Nyholm** [comment]
Excellent. Thank you

**Comment by Nyholm** [comment]
I've created a new package: https://packagist.org/packages/geocoder-php/ip-info-provider

Could you test it out and let me know if it is as you expect. If so, I'll tag 0.1.0

**Comment by romainneutron** [comment]
wow, so fast !
I'm testing now

**Comment by romainneutron** [comment]
👍 It's all food @Nyholm 
I've also pushed this one https://github.com/geocoder-php/BazingaGeocoderBundle/pull/175

**Comment by Nyholm** [comment]
Yeah. You caught me in the right moment. :)

I’ve tagged 0.1.0 now


//Tobias Nyholm

Skickat på språng

**Pull request merged**
