### PR TITLE
Use viewport as fallback

### PR DESCRIPTION
**Pull request by belendel**
Hi,

I found issue #369 but noticed it was closed. Need the functionality in my application so decided to make this PR. It will use the viewport as fallback when bounds are not present.

### CODE REVIEW

**Comment by p-j** [comment]
I've impleted it a bit differently : https://github.com/vizeat/Geocoder/commit/be62d3bacaca73295cc4ff69ed5b6037726936c7

I had a specific need : make sure I get viewport whenever possible.
A quick explanation why : 
https://www.google.com/maps/d/u/0/edit?mid=zily8X7VKwgI.kgG-JKBOOxZs
In red you have the result of the `bounds` respectively for UK & Chile.
In yellow and green you have the results for the `viewport`

I needed to get bounds that better fits the expected result for the end user rather than the strictly correct result.

I haven't written tests for it so I'm not going to make a pull request but I have its running in production for us at the moment.

**Comment by Nyholm** [comment]
I like the current implementation. But I agree with @p-j, your implementation gives better results... but it does not relate to the issue. 

@belendel I would like to merge this one but the tests fails. Would you mind rebasing on master and fix the tests?

**Comment by Nyholm** [comment]
Ping. Can you rebase this PR and make sure the tests passes?

**Comment by Nyholm** [comment]
Closed by #689

**Comment by Nyholm** [comment]
Closed by #680

**Pull request closed without merging**
