### PR TITLE
Allow psr/log 2.0 and 3.0

### PR DESCRIPTION
**Pull request by norkunas**

### CODE REVIEW

**Comment by jbelien** [comment]
Thanks for your contribution @norkunas !

Could you explain the reason behind this upgrade ?

**Comment by norkunas** [comment]
What to explain? :D I want that `composer outdated` would show empty list :stuck_out_tongue:

**Comment by jbelien** [comment]
Sounds reasonable 😄 

Have you checked that it doesn't break anything ?
What happens if you use `psr/log:2.x` or `psr/log:3.x` ?

**Comment by norkunas** [comment]
These versions just added typehints, I've checked the code and it complies contracts :)

**Review by jbelien — APPROVED** [review]

**Pull request merged**
