### PR TITLE
Add level to Address::toArray function

### LINKED ISSUE #516: Address::toArray vs AddressFactory::createFromArray - adminlevel
The `AddressFactory::createFromArray` function ask for a 'level' field for adminlevel:

```
        foreach ($this->readArrayValue($result, 'adminLevels') as $adminLevel) {
            $adminLevels[] = new AdminLevel(
                intval($this->readStringValue($adminLevel, 'level')),
                $this->readStringValue($adminLevel, 'name'),
                $this->readStringValue($adminLevel, 'code')
            );
        }
```

But the `Address::toArray` does not provide it:

```
    foreach ($this->adminLevels as $adminLevel) {
        $adminLevels[$adminLevel->getLevel()] = [
            'name'  => $adminLevel->getName(),
            'code'  => $adminLevel->getCode(),
        ];
    }
```

Should we add it ?

```
    foreach ($this->adminLevels as $adminLevel) {
        $adminLevels[$adminLevel->getLevel()] = [
            'name'  => $adminLevel->getName(),
            'code'  => $adminLevel->getCode(),
            'level' => $adminLevel->getLevel()
        ];
    }
```

or modify  `AddressFactory::createFromArray` to use the array key?

Exemple:

```
    $results     = $geocoder->using('cache')->geocode('12 avenue des champs Elysées, Paris, France');
    $arrayResult = $results->first()->toArray();
    $factory = new AddressFactory();
    $address = $factory->createFromArray([$arrayResult]);
```

Throw this exception:

```
Administrative level should be an integer in [1,5], 0 given
500 Internal Server Error - OutOfBoundsException
```

### PR DESCRIPTION
**Pull request by AntoineLemaire**
Fix #516

### CODE REVIEW

**Comment by willdurand** [comment]
Well, the index already provides the level. Why not using it?

**Comment by Nyholm** [comment]
Oh, I did also miss that. Sorry-

**Comment by AntoineLemaire** [comment]
It's what I explained in my issue. Why toArray function result could not be used directly by fromArray function without modifications of this array?

**Comment by willdurand** [comment]
Ah. Did not read the whole issue sorry... So, does it work better now? It is a simple addition, so if you add a test case for this, then it's good to me!

**Comment by AntoineLemaire** [comment]
How do you see that? Add `testToArray()` to all Provider tests files? Or choose a random provider in `AddressFactoryTest` and test `toArray`, `fromArray` and assertSame on addresses?

**Comment by willdurand** [comment]
Is there any test class for the `Address` class?

**Comment by AntoineLemaire** [comment]
No, only `AddressFactory`

**Comment by willdurand** [comment]
Then, maybe you could create this test class

**Comment by AntoineLemaire** [comment]
Done & commits squash

**Comment by willdurand** [comment]
Can you also provide a test for this `toArray/fromArray` thing please?

**Comment by AntoineLemaire** [comment]
Done & commits squash

**Comment by willdurand** [comment]
Looks good to me!

**Comment by vicchi** [comment]
+1 LGTM

**Comment by Nyholm** [comment]
Hey @AntoineLemaire. 

Sorry for the delay with this PR. If you solve the merge conflicts I'll be happy to merge

**Comment by Nyholm** [comment]
Fixed by #622

**Comment by AntoineLemaire** [comment]
Oh sorry, I missed that! Thanks for merged it 👍

**Pull request closed without merging**
