### PR TITLE
Add geo array dumper

### PR DESCRIPTION
**Pull request by norkunas**
Replaces #517

### CODE REVIEW

**Comment by drupol** [comment]
👍

**Comment by Nyholm** [comment]
Thank you. You are missing tests and documentation. Here are the tests you've previously written: https://github.com/norkunas/Geocoder/blob/674efb9adc1fa495d781907a53a9664ae49f3e44/tests/Geocoder/Tests/Dumper/GeoArrayTest.php

**Comment by norkunas** [comment]
👍

**Comment by Nyholm** [comment]
This feature will not be in a release until v4.0. I've created a milestone for that version https://github.com/geocoder-php/Geocoder/milestone/3

Feel free to make another PR.

**Pull request merged**
