### PR TITLE
Allow `psr/simple-cache` v2 and v3

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
Impossible to tell if these failures are related to this PR or if main is just broken. @jbelien any idea?

**Comment by jbelien** [comment]
@ruudk I've fixed the tests.

Can you check what needs to be done to make your PR works for [PHP 8.0](https://github.com/geocoder-php/Geocoder/runs/5166431893?check_suite_focus=true) and [PHP 8.1](https://github.com/geocoder-php/Geocoder/runs/5166432354?check_suite_focus=true) ? Thanks.

**Comment by gnumoksha** [comment]
> @ruudk I've fixed the tests.
> 
> Can you check what needs to be done to make your PR works for [PHP 8.0](https://github.com/geocoder-php/Geocoder/runs/5166431893?check_suite_focus=true) and [PHP 8.1](https://github.com/geocoder-php/Geocoder/runs/5166432354?check_suite_focus=true) ? Thanks.

https://github.com/geocoder-php/Geocoder/pull/1150

**Comment by jbelien** [comment]
Replaced by #1150 

@ruudk You has been added as co-author (see 9ab70d65b434a3daa028d6aebb8f122dd32ee80f)

**Pull request closed without merging**
