### PR TITLE
[Google Places] fix + support both reverse modes: Search & Nearby

### PR DESCRIPTION
**Pull request by wivaku**
Coming from https://github.com/geocoder-php/Geocoder/issues/1063

The reverse query was using `Search` (requires Type). 
This PR adds support for `Nearby`, which can be used with:
rankby:prominence + radius (=default `Nearby` combination)
rankby:distance + type/keyword/name (distance + type is very similar to the original `Search`)

Note: `Search` returns formatted_address, `Nearby` returns vicinity.

### CODE REVIEW

**Comment by jbelien** [comment]
Thanks a lot !

Before I review it, could you sure it respect our "style standard" (see [StyleCI report](https://github.styleci.io/analyses/2Qg2a4)) ?

**Comment by wivaku** [comment]
will do. Having trouble to merge the commits, so will submit new PR. Can close this one.

**Comment by jbelien** [comment]
> Having trouble to merge the commits, so will submit new PR.

You didn't need to close this PR !
Every change that you commit to your branch `wivaku:issue-1063` will apply to this commit !

**Comment by wivaku** [comment]
Ah good to know. I saw the contribute notes that states the commits needed to be squashed, and I had trouble getting that to work.

**Comment by jbelien** [comment]
> the commits needed to be squashed

That will be my part, don't bother with it :)
You can just push your commits to your branch and it will update the PR !
I will then squash and merge your PR.

**Comment by wivaku** [comment]
Thanks. Already created the new one: https://github.com/geocoder-php/Geocoder/pull/1070

**Pull request closed without merging**
