### PR TITLE
Add name for PhotonAddress

### PR DESCRIPTION
**Pull request by nihilsen**
This PR adds "name" for the photon provider.

Two new methods are added to `PhotonAddress`: `getName()` and `withName($name)`

### CODE REVIEW

**Comment by jbelien** [comment]
Thanks @nihilsen ! 👍 

Could you add a new test for that field ?

**Comment by nihilsen** [comment]
Tests added.

It occurred to me that the Photon API doesn't always provide a "name" property that we can use as the display name.

That's not very useful, so in those cases I think it would be appropriate to construct a placeholder display name using the address components. This produces a display name similar to that given by the Nominatim provider.

**Comment by jbelien** [comment]
> It occurred to me that the Photon API doesn't always provide a "name" property that we can use as the display name.

No, we do not "touch" the result returned by an API.
If there is no `name` property fill, the `name` should stay null.
Please revert commit 4b91de7 and add a test for a request that returns a `name` property.

Thanks.

**Review by jbelien — CHANGES_REQUESTED** [review]
See https://github.com/geocoder-php/Geocoder/pull/1106#issuecomment-760456241

**Comment by nihilsen** [comment]
> No, we do not "touch" the result returned by an API.

Got it. That seems reasonable.

**Review by jbelien — CHANGES_REQUESTED** [review]
- We try to keep properties as defined by the API. Instead of `displayName`, could you rename it to `name`, `getName()`, `withName()` ?

- Could you create a new separated test (instead of including your test to `testGeocodeQuery()`) ?

Thanks.

**Comment by nihilsen** [comment]
> Instead of displayName, could you rename it to name, getName(), withName() ?

You got it.

Tests separated.

**Review by jbelien — APPROVED** [review]

**Comment by jbelien** [comment]
Thanks @nihilsen !

**Pull request merged**
