### PR TITLE
[MaxMindBinary] Issue #946 - Apply utf8_encode only if the field is not null

### PR DESCRIPTION
**Pull request by xserrat**
Hi,

This PR fixes the #946 :)

### CODE REVIEW

**Comment by jbelien** [comment]
Looking good, thanks !

I'll merge it ASAP 👍

**Comment by xserrat** [comment]
Thanks @jbelien ! 👌

**Comment by xserrat** [comment]
Hi @jbelien ,

Do you know when do you plan to launch a new release with this change?

Thank you so much!

**Comment by jbelien** [comment]
Hello @xserrat ,

It's released since 26 of April : https://github.com/geocoder-php/maxmind-binary-provider/releases/tag/4.0.1

**Comment by xserrat** [comment]
Perfect @jbelien ,

Thanks! :)

**Comment by xserrat** [comment]
Hi @jbelien,

I've just reviewed your integration and it's ok but in this repository (https://github.com/geocoder-php/Geocoder) there's no tag created (only the merge into the master branch). So, I cannot point to this fix in my composer.json.

Could you create a tag also in this repo?

Thanks again :

**Pull request merged**
