### PR TITLE
[FreeGeoIp] Add the missing timezone field

### PR DESCRIPTION
**Pull request by francoispluchino**
Add the missing `timezone` field for `FreeGeoIp` provider.

### CODE REVIEW

**Comment by francoispluchino** [comment]
@willdurand Do you think this PR perhaps merged?

**Comment by mdoelker** [comment]
:+1: for merge :)

**Comment by francoispluchino** [comment]
@Baachi Thanks!

**Comment by Baachi** [comment]
No problem :+1:

**Pull request merged**
