### PR TITLE
Adding cache provider

### PR DESCRIPTION
**Pull request by Nyholm**
This provider is caching the result of other providers with simple cache. 

FYI: HTTP providers may use the cache plugin to HTTPlug

### CODE REVIEW

**Comment by Nyholm** [comment]
Ping @mikebronner 
This might be something for Laravel?

**Comment by mikebronner** [comment]
@Nyholm We already have caching in place using Laravel's native cache provider :) Or were you thinking something else?

**Comment by Nyholm** [comment]
Okey, I must have missed that. Using Laravel's native cache is better of course.

**Comment by mikebronner** [comment]
No worries :) just happened a week ago! haha

**Pull request merged**
